use std::fs;
#[cfg(unix)]
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

const APP_DIR_NAME: &str = "red-cell-client";
const CONFIG_FILE_NAME: &str = "client.toml";
const SCRIPTS_DIR_NAME: &str = "scripts";

/// Persisted client preferences loaded between sessions.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct LocalConfig {
    /// Last-used teamserver WebSocket URL.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub server_url: Option<String>,
    /// Last-used operator username.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// Directory containing client-side Python scripts.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scripts_dir: Option<PathBuf>,
    /// Path to a custom CA certificate PEM file for teamserver verification.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ca_cert: Option<PathBuf>,
    /// SHA-256 fingerprint (hex) of the pinned teamserver certificate.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cert_fingerprint: Option<String>,
    /// Per-invocation timeout (in seconds) for Python script callbacks.
    ///
    /// When a callback does not return within this many seconds a
    /// `KeyboardInterrupt` is injected into the interpreter and an `ERROR`-level
    /// log message is emitted.  Defaults to 10 seconds when omitted.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub python_script_timeout_secs: Option<u64>,
    /// Directory for daily rolling log files (default: see [`crate::logging::default_log_dir`]).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub log_dir: Option<PathBuf>,
    /// Log filter directives (`info`, `debug`, `warn`, or `target=level` lists).
    /// Ignored when `RUST_LOG` is set to a valid value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub log_level: Option<String>,
    /// API key used to authenticate REST API calls (e.g. for the audit log panel).
    ///
    /// Generated by the teamserver and configured in the HCL profile under
    /// `[Teamserver.Api.Keys]`. The GUI uses this key for direct REST calls that
    /// are not routed through the operator WebSocket.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
}

impl LocalConfig {
    /// Load the local config from the platform config directory.
    ///
    /// Returns the default config if the file does not exist or cannot be parsed.
    pub fn load() -> Self {
        Self::load_with_path(config_file_path())
    }

    /// Load the local config from a specific path.
    ///
    /// Returns the default config if the file does not exist or cannot be parsed.
    pub fn load_from(path: &std::path::Path) -> Self {
        match fs::read_to_string(path) {
            Ok(contents) => match toml::from_str(&contents) {
                Ok(config) => config,
                Err(error) => {
                    tracing::warn!(
                        path = %path.display(),
                        %error,
                        "failed to parse client config; falling back to defaults",
                    );
                    Self::default()
                }
            },
            Err(_) => Self::default(),
        }
    }

    /// Persist the local config to the platform config directory.
    ///
    /// Returns an error if the config directory is unavailable, if parent
    /// directories cannot be created, or if the file cannot be written.
    /// Callers should log or surface this error — the config holds
    /// security-relevant state (TLS trust material, pinned fingerprints) and
    /// silent loss will cause unexpected fallback to defaults on next launch.
    pub fn save(&self) -> Result<(), std::io::Error> {
        self.save_with_path(config_file_path())
    }

    /// Persist the local config to a specific path.
    ///
    /// Creates parent directories as needed.
    /// On Unix the file is created with mode 0600 (owner-only read/write).
    ///
    /// Returns an error if directory creation or the file write fails.
    pub fn save_to(&self, path: &std::path::Path) -> Result<(), std::io::Error> {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }

        let contents = toml::to_string_pretty(self)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
        write_config_file(path, contents.as_bytes())
    }

    /// Resolve the configured scripts directory, falling back to the default location.
    pub fn resolved_scripts_dir(&self) -> Option<PathBuf> {
        self.scripts_dir.clone().or_else(default_scripts_dir)
    }

    fn load_with_path(path: Option<PathBuf>) -> Self {
        let Some(path) = path else {
            return Self::default();
        };
        Self::load_from(&path)
    }

    fn save_with_path(&self, path: Option<PathBuf>) -> Result<(), std::io::Error> {
        let Some(path) = path else {
            return Ok(());
        };
        self.save_to(&path)
    }
}

/// Write `data` to `path` with mode 0600 on Unix (owner-only read/write).
///
/// On non-Unix platforms this uses default permissions.
fn write_config_file(path: &std::path::Path, data: &[u8]) -> std::io::Result<()> {
    use std::io::Write;

    #[cfg(unix)]
    let mut file =
        fs::OpenOptions::new().write(true).create(true).truncate(true).mode(0o600).open(path)?;

    #[cfg(not(unix))]
    let mut file = fs::OpenOptions::new().write(true).create(true).truncate(true).open(path)?;

    file.write_all(data)?;

    // On Unix, .mode() only applies at creation time. If the file already
    // existed with looser permissions, explicitly tighten them.
    #[cfg(unix)]
    fs::set_permissions(path, fs::Permissions::from_mode(0o600))?;

    Ok(())
}

fn config_file_path() -> Option<PathBuf> {
    dirs::config_dir().map(|dir| dir.join(APP_DIR_NAME).join(CONFIG_FILE_NAME))
}

pub(crate) fn default_scripts_dir() -> Option<PathBuf> {
    dirs::config_dir().map(|dir| dir.join(APP_DIR_NAME).join(SCRIPTS_DIR_NAME))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_config_has_no_values() {
        let config = LocalConfig::default();
        assert_eq!(config.server_url, None);
        assert_eq!(config.username, None);
        assert_eq!(config.scripts_dir, None);
        assert_eq!(config.ca_cert, None);
        assert_eq!(config.cert_fingerprint, None);
        assert_eq!(config.python_script_timeout_secs, None);
        assert_eq!(config.log_dir, None);
        assert_eq!(config.log_level, None);
    }

    #[test]
    fn python_script_timeout_secs_round_trips() {
        let config = LocalConfig { python_script_timeout_secs: Some(30), ..LocalConfig::default() };

        let serialized = toml::to_string_pretty(&config)
            .unwrap_or_else(|error| panic!("serialization should succeed: {error}"));
        let deserialized: LocalConfig = toml::from_str(&serialized)
            .unwrap_or_else(|error| panic!("deserialization should succeed: {error}"));

        assert_eq!(deserialized.python_script_timeout_secs, Some(30));
    }

    #[test]
    fn python_script_timeout_secs_absent_when_none() {
        let config = LocalConfig::default();
        let serialized = toml::to_string_pretty(&config)
            .unwrap_or_else(|error| panic!("serialization should succeed: {error}"));
        assert!(
            !serialized.contains("python_script_timeout_secs"),
            "None timeout should not appear in serialized config"
        );
    }

    #[test]
    fn config_round_trips_through_toml() {
        let config = LocalConfig {
            server_url: Some("wss://10.0.0.1:40056/havoc/".to_owned()),
            username: Some("operator".to_owned()),
            scripts_dir: Some(PathBuf::from("/tmp/red-cell-client/scripts")),
            ca_cert: Some(PathBuf::from("/tmp/ca.pem")),
            cert_fingerprint: Some("abcdef0123456789".to_owned()),
            python_script_timeout_secs: None,
            log_dir: Some(PathBuf::from("/tmp/red-cell-logs")),
            log_level: Some("debug".to_owned()),
            api_key: None,
        };

        let serialized = toml::to_string_pretty(&config)
            .unwrap_or_else(|error| panic!("serialization should succeed: {error}"));
        let deserialized: LocalConfig = toml::from_str(&serialized)
            .unwrap_or_else(|error| panic!("deserialization should succeed: {error}"));

        assert_eq!(deserialized, config);
    }

    #[test]
    fn config_deserializes_partial_toml() {
        let toml_str = r#"server_url = "wss://example.com/havoc/""#;
        let config: LocalConfig = toml::from_str(toml_str)
            .unwrap_or_else(|error| panic!("partial deserialization should succeed: {error}"));

        assert_eq!(config.server_url.as_deref(), Some("wss://example.com/havoc/"));
        assert_eq!(config.username, None);
        assert_eq!(config.scripts_dir, None);
    }

    #[test]
    fn config_deserializes_empty_toml() {
        let config: LocalConfig =
            toml::from_str("").unwrap_or_else(|error| panic!("empty toml should parse: {error}"));

        assert_eq!(config, LocalConfig::default());
    }

    #[test]
    fn save_and_load_round_trip_via_tempdir() {
        let dir = tempfile::tempdir()
            .unwrap_or_else(|error| panic!("tempdir creation should succeed: {error}"));
        let path = dir.path().join("client.toml");

        let config = LocalConfig {
            server_url: Some("wss://10.0.0.5:9999/havoc/".to_owned()),
            username: Some("admin".to_owned()),
            scripts_dir: Some(dir.path().join("scripts")),
            ca_cert: None,
            cert_fingerprint: None,
            python_script_timeout_secs: None,
            log_dir: None,
            log_level: None,
            api_key: None,
        };

        config.save_to(&path).unwrap_or_else(|e| panic!("save_to should succeed: {e}"));
        let loaded = LocalConfig::load_from(&path);

        assert_eq!(loaded, config);
    }

    #[test]
    fn load_from_returns_default_for_invalid_toml() {
        let dir = tempfile::tempdir()
            .unwrap_or_else(|error| panic!("tempdir creation should succeed: {error}"));
        let path = dir.path().join("client.toml");

        fs::write(&path, "server_url = [")
            .unwrap_or_else(|error| panic!("write should succeed: {error}"));

        assert_eq!(LocalConfig::load_from(&path), LocalConfig::default());
    }

    #[test]
    fn load_from_returns_default_for_nonexistent_path() {
        let path = std::path::Path::new("/tmp/red-cell-nonexistent-dir/client.toml");
        assert_eq!(LocalConfig::load_from(path), LocalConfig::default());
    }

    #[test]
    fn load_with_missing_config_dir_returns_default() {
        assert_eq!(LocalConfig::load_with_path(None), LocalConfig::default());
    }

    #[test]
    fn save_with_missing_config_dir_is_noop() {
        let config = LocalConfig {
            server_url: Some("wss://10.0.0.5:9999/havoc/".to_owned()),
            username: Some("admin".to_owned()),
            scripts_dir: Some(PathBuf::from("/tmp/red-cell-client/scripts")),
            ca_cert: Some(PathBuf::from("/tmp/ca.pem")),
            cert_fingerprint: Some("abcdef0123456789".to_owned()),
            python_script_timeout_secs: None,
            log_dir: None,
            log_level: None,
            api_key: None,
        };

        // None path is a documented no-op — must succeed.
        config.save_with_path(None).unwrap_or_else(|e| panic!("None path should be a no-op: {e}"));
    }

    #[test]
    fn resolved_scripts_dir_prefers_explicit_value() {
        let config = LocalConfig {
            scripts_dir: Some(PathBuf::from("/tmp/client-scripts")),
            ..LocalConfig::default()
        };

        assert_eq!(config.resolved_scripts_dir(), Some(PathBuf::from("/tmp/client-scripts")));
    }

    #[test]
    fn resolved_scripts_dir_falls_back_to_default_location_when_unset() {
        let config = LocalConfig::default();
        assert_eq!(config.scripts_dir, None);

        let resolved = config.resolved_scripts_dir();
        assert_eq!(resolved, default_scripts_dir());

        // When the platform provides a config dir, verify the fallback ends
        // with the expected "scripts" suffix.
        if let Some(ref path) = resolved {
            assert!(
                path.ends_with(SCRIPTS_DIR_NAME),
                "fallback path should end with {SCRIPTS_DIR_NAME:?}, got {path:?}",
            );
        }
    }

    #[test]
    fn resolved_scripts_dir_with_none_differs_from_explicit_custom_path() {
        let custom = PathBuf::from("/tmp/my-custom-scripts");
        let config_with_custom =
            LocalConfig { scripts_dir: Some(custom.clone()), ..LocalConfig::default() };
        let config_without = LocalConfig::default();

        let resolved_custom = config_with_custom.resolved_scripts_dir();
        let resolved_default = config_without.resolved_scripts_dir();

        assert_eq!(resolved_custom, Some(custom));
        assert_ne!(
            resolved_custom, resolved_default,
            "explicit scripts_dir should differ from the platform default",
        );
    }

    #[test]
    fn resolved_scripts_dir_returns_none_when_platform_config_dir_unavailable() {
        // On platforms where dirs::config_dir() returns None (e.g. some CI
        // containers), both default_scripts_dir() and the fallback in
        // resolved_scripts_dir() must return None.
        let config = LocalConfig::default();

        if default_scripts_dir().is_some() {
            // Cannot simulate dirs::config_dir() returning None without mocking,
            // so just verify consistency: resolved should equal default.
            assert_eq!(config.resolved_scripts_dir(), default_scripts_dir());
            return;
        }

        assert_eq!(config.resolved_scripts_dir(), None);
    }

    #[test]
    fn default_scripts_dir_returns_expected_suffix() {
        // Verify that default_scripts_dir() produces a path under the
        // platform config dir with the correct app + scripts subdirectory.
        let result = default_scripts_dir();

        if let Some(ref path) = result {
            let expected = dirs::config_dir()
                .expect("config_dir should be Some when default_scripts_dir is Some")
                .join(APP_DIR_NAME)
                .join(SCRIPTS_DIR_NAME);
            assert_eq!(path, &expected);
        }
        // If result is None, dirs::config_dir() is unavailable — nothing to assert.
    }

    #[test]
    fn load_from_returns_default_for_binary_garbage() {
        let dir = tempfile::tempdir()
            .unwrap_or_else(|error| panic!("tempdir creation should succeed: {error}"));
        let path = dir.path().join("client.toml");

        fs::write(&path, b"\x00\x01\x02\xff\xfe\xfd")
            .unwrap_or_else(|error| panic!("write should succeed: {error}"));

        assert_eq!(LocalConfig::load_from(&path), LocalConfig::default());
    }

    #[test]
    fn load_from_returns_default_for_truncated_toml() {
        let dir = tempfile::tempdir()
            .unwrap_or_else(|error| panic!("tempdir creation should succeed: {error}"));
        let path = dir.path().join("client.toml");

        // Valid key but value is truncated mid-string (no closing quote).
        fs::write(&path, "server_url = \"wss://10.0.0.1:40056")
            .unwrap_or_else(|error| panic!("write should succeed: {error}"));

        assert_eq!(LocalConfig::load_from(&path), LocalConfig::default());
    }

    #[test]
    fn load_from_returns_default_for_wrong_field_type() {
        let dir = tempfile::tempdir()
            .unwrap_or_else(|error| panic!("tempdir creation should succeed: {error}"));
        let path = dir.path().join("client.toml");

        // server_url should be a string, not an integer.
        fs::write(&path, "server_url = 42")
            .unwrap_or_else(|error| panic!("write should succeed: {error}"));

        // toml::from_str fails on type mismatch → unwrap_or_default → full default.
        assert_eq!(LocalConfig::load_from(&path), LocalConfig::default());
    }

    #[test]
    fn load_from_returns_default_when_valid_field_mixed_with_wrong_type() {
        let dir = tempfile::tempdir()
            .unwrap_or_else(|error| panic!("tempdir creation should succeed: {error}"));
        let path = dir.path().join("client.toml");

        // username is valid, but scripts_dir is an integer instead of a string.
        let content = "username = \"operator\"\nscripts_dir = 12345\n";
        fs::write(&path, content).unwrap_or_else(|error| panic!("write should succeed: {error}"));

        // The entire deserialization fails, so we get full default — not a partial
        // config with username set.
        assert_eq!(LocalConfig::load_from(&path), LocalConfig::default());
    }

    #[test]
    fn load_from_returns_default_for_array_instead_of_table() {
        let dir = tempfile::tempdir()
            .unwrap_or_else(|error| panic!("tempdir creation should succeed: {error}"));
        let path = dir.path().join("client.toml");

        // The file is valid TOML (an array) but not a valid LocalConfig (expects a table).
        fs::write(&path, "[[items]]\nname = \"foo\"\n")
            .unwrap_or_else(|error| panic!("write should succeed: {error}"));

        assert_eq!(LocalConfig::load_from(&path), LocalConfig::default());
    }

    #[test]
    fn load_from_returns_default_for_duplicate_keys() {
        let dir = tempfile::tempdir()
            .unwrap_or_else(|error| panic!("tempdir creation should succeed: {error}"));
        let path = dir.path().join("client.toml");

        let content = "server_url = \"wss://a\"\nserver_url = \"wss://b\"\n";
        fs::write(&path, content).unwrap_or_else(|error| panic!("write should succeed: {error}"));

        // Duplicate keys are a TOML parse error → full default.
        assert_eq!(LocalConfig::load_from(&path), LocalConfig::default());
    }

    #[test]
    fn load_from_handles_crafted_server_url_with_special_chars() {
        let dir = tempfile::tempdir()
            .unwrap_or_else(|error| panic!("tempdir creation should succeed: {error}"));
        let path = dir.path().join("client.toml");

        // A server_url with path traversal and SQL-like injection attempts.
        let crafted = "wss://evil.com/'; DROP TABLE operators;--/../../../etc/passwd";
        let content = format!("server_url = \"{crafted}\"\n");
        fs::write(&path, &content).unwrap_or_else(|error| panic!("write should succeed: {error}"));

        let config = LocalConfig::load_from(&path);
        // The value must be stored verbatim — no interpretation or execution.
        assert_eq!(config.server_url.as_deref(), Some(crafted));
        // All other fields default.
        assert_eq!(config.username, None);
        assert_eq!(config.scripts_dir, None);
    }

    #[test]
    fn load_from_handles_crafted_username_with_embedded_toml() {
        let dir = tempfile::tempdir()
            .unwrap_or_else(|error| panic!("tempdir creation should succeed: {error}"));
        let path = dir.path().join("client.toml");

        // Username containing TOML-like syntax — must be treated as an opaque string.
        let content = "username = \"admin\\nserver_url = \\\"wss://hijacked\\\"\"\n";
        fs::write(&path, content).unwrap_or_else(|error| panic!("write should succeed: {error}"));

        let config = LocalConfig::load_from(&path);
        // The crafted value should be stored as a single string, not interpreted
        // as a second key.
        assert!(config.username.is_some());
        assert_eq!(config.server_url, None, "TOML injection must not set server_url");
    }

    #[test]
    fn load_from_handles_extremely_long_values() {
        let dir = tempfile::tempdir()
            .unwrap_or_else(|error| panic!("tempdir creation should succeed: {error}"));
        let path = dir.path().join("client.toml");

        let long_url = format!("wss://{}", "A".repeat(100_000));
        let content = format!("server_url = \"{long_url}\"\n");
        fs::write(&path, &content).unwrap_or_else(|error| panic!("write should succeed: {error}"));

        let config = LocalConfig::load_from(&path);
        assert_eq!(config.server_url.as_deref(), Some(long_url.as_str()));
    }

    #[test]
    fn load_from_ignores_unknown_fields_and_preserves_known() {
        let dir = tempfile::tempdir()
            .unwrap_or_else(|error| panic!("tempdir creation should succeed: {error}"));
        let path = dir.path().join("client.toml");

        let content = "username = \"op1\"\nunknown_field = \"surprise\"\nextra = 999\n";
        fs::write(&path, content).unwrap_or_else(|error| panic!("write should succeed: {error}"));

        // serde default behaviour: unknown fields are ignored (no deny_unknown_fields).
        let config = LocalConfig::load_from(&path);
        assert_eq!(config.username.as_deref(), Some("op1"));
    }

    #[cfg(unix)]
    #[test]
    fn save_to_creates_file_with_restrictive_permissions() {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::tempdir()
            .unwrap_or_else(|error| panic!("tempdir creation should succeed: {error}"));
        let path = dir.path().join("client.toml");

        let config = LocalConfig {
            server_url: Some("wss://10.0.0.1:40056/havoc/".to_owned()),
            username: Some("operator".to_owned()),
            ..LocalConfig::default()
        };

        config.save_to(&path).unwrap_or_else(|e| panic!("save_to should succeed: {e}"));

        let metadata =
            fs::metadata(&path).unwrap_or_else(|error| panic!("metadata should succeed: {error}"));
        let mode = metadata.permissions().mode() & 0o777;
        assert_eq!(mode, 0o600, "config file should be owner-only (0600), got {mode:#o}");
    }

    #[cfg(unix)]
    #[test]
    fn save_to_tightens_permissions_on_existing_file() {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::tempdir()
            .unwrap_or_else(|error| panic!("tempdir creation should succeed: {error}"));
        let path = dir.path().join("client.toml");

        // Create an initial file with permissive (0o644) permissions.
        fs::write(&path, "old content")
            .unwrap_or_else(|error| panic!("initial write should succeed: {error}"));
        fs::set_permissions(&path, fs::Permissions::from_mode(0o644))
            .unwrap_or_else(|error| panic!("chmod should succeed: {error}"));

        let config = LocalConfig {
            server_url: Some("wss://new-server/havoc/".to_owned()),
            ..LocalConfig::default()
        };
        config.save_to(&path).unwrap_or_else(|e| panic!("save_to should succeed: {e}"));

        // Verify permissions were tightened.
        let mode = fs::metadata(&path)
            .unwrap_or_else(|error| panic!("metadata should succeed: {error}"))
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(mode, 0o600, "permissions should be tightened to 0600, got {mode:#o}");

        // Verify content was updated.
        let loaded = LocalConfig::load_from(&path);
        assert_eq!(loaded.server_url.as_deref(), Some("wss://new-server/havoc/"));
    }

    /// `save_to()` must return an `Err` (not panic) when the target path is
    /// inside a read-only directory, so callers can surface the failure.
    #[cfg(unix)]
    #[test]
    fn save_to_returns_error_for_unwritable_path() {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::tempdir()
            .unwrap_or_else(|error| panic!("tempdir creation should succeed: {error}"));
        let readonly_dir = dir.path().join("readonly");
        fs::create_dir(&readonly_dir)
            .unwrap_or_else(|error| panic!("mkdir should succeed: {error}"));

        // Lock down the directory so writes inside it are rejected.
        fs::set_permissions(&readonly_dir, fs::Permissions::from_mode(0o444))
            .unwrap_or_else(|error| panic!("chmod should succeed: {error}"));

        let path = readonly_dir.join("client.toml");
        let config = LocalConfig {
            server_url: Some("wss://10.0.0.1:40056/havoc/".to_owned()),
            username: Some("operator".to_owned()),
            ..LocalConfig::default()
        };

        // Must return Err, not panic.
        assert!(config.save_to(&path).is_err(), "save_to should return Err for an unwritable path",);

        // The file must not have been created.
        assert!(!path.exists(), "config file should not exist under a read-only directory");

        // Restore write permission so tempdir cleanup can remove it.
        fs::set_permissions(&readonly_dir, fs::Permissions::from_mode(0o755))
            .unwrap_or_else(|error| panic!("restoring permissions should succeed: {error}"));
    }

    /// `save()` must not panic regardless of whether a config directory is
    /// available.  The return value (Ok or Err) depends on the host environment
    /// and is intentionally ignored here; we only assert no panic.
    #[test]
    fn public_save_does_not_panic() {
        let config = LocalConfig {
            server_url: Some("wss://10.0.0.1:40056/havoc/".to_owned()),
            ..LocalConfig::default()
        };
        let _ = config.save();
    }
}
